#!/usr/bin/env bash
# Shared constants + helpers for deploy scripts.
set -euo pipefail

# ─── Configuration ────────────────────────────────────────────────
export AWS_REGION="us-east-1"
export AWS_DEFAULT_REGION="us-east-1"

PROJECT_TAG="aifirstapp-collections"
KEY_NAME="${PROJECT_TAG}-key"
SG_NAME="${PROJECT_TAG}-sg"
INSTANCE_NAME="${PROJECT_TAG}-host"
INSTANCE_TYPE="t3.xlarge"
EBS_SIZE_GB="50"

# DNS
HOSTED_ZONE_ID="Z05446501WDE1E8N4CZ0K"   # aifirstapplication.com
SITE_HOSTNAME="collections.aifirstapplication.com"
ACME_EMAIL="naveen.balawat@gmail.com"

# Paths
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
STATE_FILE="${REPO_ROOT}/.deploy-state"
KEY_FILE="${REPO_ROOT}/ec2-key.pem"

# ─── State load/save ────────────────────────────────────────────────
load_state() {
  if [[ -f "${STATE_FILE}" ]]; then
    # shellcheck disable=SC1090
    source "${STATE_FILE}"
  fi
}

save_state() {
  cat > "${STATE_FILE}" <<EOF
# Auto-generated by scripts/deploy/. Do not commit.
INSTANCE_ID="${INSTANCE_ID:-}"
PUBLIC_IP="${PUBLIC_IP:-}"
PUBLIC_DNS="${PUBLIC_DNS:-}"
SG_ID="${SG_ID:-}"
KEY_NAME="${KEY_NAME}"
SITE_HOSTNAME="${SITE_HOSTNAME}"
EOF
}

# ─── Logging ────────────────────────────────────────────────────────
log()  { printf "\033[1;34m→\033[0m %s\n" "$*"; }
ok()   { printf "\033[1;32m✓\033[0m %s\n" "$*"; }
warn() { printf "\033[1;33m!\033[0m %s\n" "$*"; }
err()  { printf "\033[1;31m✗\033[0m %s\n" "$*" >&2; }

ssh_into() {
  ssh -i "${KEY_FILE}" -o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/dev/null \
      -o LogLevel=ERROR "ec2-user@${PUBLIC_IP}" "$@"
}
